var path = require('path');
var webpack = require('webpack');

var TimestampWebpackPlugin = require('timestamp-webpack-plugin');

module.exports = {
    context: path.resolve('js'),
    entry: ["./app"],
    output: {
        path: path.resolve('build/'),
        publicPath: '/public/assets/',
        filename: "bundle.js"
    },
    watch: true,

    devServer: {
        contentBase: 'public'
    },

    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery"
        }),
        new TimestampWebpackPlugin({
            path: __dirname,
            filename: 'timestamp.json'
        }),
        new webpack.BannerPlugin("****\nGenerated by webpack\n*****\n")

    ],

    module: {
        rules: [
            {
                test: /\.css$/,
                exclude: /node_modules/,
                loader: "style-loader!css-loader"
            },
            {
                test: /\.json$/,
                exclude: /node_modules/,
                loader: "json-loader!" + path.resolve('loaders/strip')
            }
        ]
    },
    resolve: {
        extensions: ['.js']
    }
}